import MobileBanner from './img/banner/mobile_banner.jpg';
import MobileADS from './img/banner/ads_mobile.jpg';
import MobileADS2 from './img/banner/ADS2.jpg';
import Health from './img/brands/health_2.png';
import Shirt from './img/brands/shirt.png';
import Phone from './img/brands/phone_2.png';
import AirPod from './img/brands/earbug.png';

import Nintendo from './img/brands/nintenddo.png';
import NintendoBg from './img/brands/nitendo_bg.png';
import N_One from './img/brands/n1.png';
import N_Two from './img/brands/n2.png';
import N_Three from './img/brands/n3.png';
import VanOfTheWall from './img/brands/vanofthewall.png';
import Mi from './img/brands/mi.png';
import Media from './img/brands/media.png';
import Toyota from './img/brands/toyota.png';
import Sony from './img/brands/sony.png';

// best selling
import BsOne from './img/bestselling/bs_one.png';
import BsTwo from './img/bestselling/bs_two.png';
// shop
import United from './img/shop/united.png';
import UnitedOne from './img/shop/united_one.png';
import UnitedTwo from './img/shop/united_two.png';
import UnitedThree from './img/shop/united_three.png';
import Liquor from './img/shop/liquor.png';
import LiquorOne from './img/shop/liquor_one.png';
import LiquorTwo from './img/shop/liquor_two.png';
import LiquorThree from './img/shop/liquor_three.png';
import Beauty from './img/shop/beauty.png';
import BeautyOne from './img/shop/beauty_one.png';
import BeautyTwo from './img/shop/beauty_two.png';
import BeautyThree from './img/shop/beauty_three.png';
import Fried from './img/shop/fried.png';
import FriedOne from './img/shop/fried_one.png';
import FriedTwo from './img/shop/fried_two.png';
import FriedThree from './img/shop/fried_three.png';
import Shwe from './img/shop/shwe.png';
import ShweOne from './img/shop/shwe_one.png';
import ShweTwo from './img/shop/shwe_two.png';
import ShweThree from './img/shop/united_two.png';
import FlashSaleBg from './img/flashSale/flashsalebg.png';
import FlashOne from './img/flashSale/protein.jpg';
import FlashTwo from './img/flashSale/bleaching.jpg';
import FlashThree from './img/flashSale/cereal.jpg';
import LatesOne from './img/latest/latest_one.jpg';
import LatesTow from './img/latest/latest_two.jpg';
import LatesThree from './img/latest/latest_three.jpg';
import LatesFour from './img/latest/latest_four.jpg';
import LatesFive from './img/latest/latest_five.jpg';
import LatesSix from './img/latest/latest_six.jpg';
// product list
import MobileHealthBg from './img/productlistbycat/skin.png';
import Mh_One from './img/productlistbycat/mh_1.png';
import Mh_Two from './img/productlistbycat/mh_2.png';
import Mh_Three from './img/productlistbycat/mh_3.png';
import Mh_Four from './img/productlistbycat/mh_4.png';

import MobilePhoneBg from './img/productlistbycat/phone.png';
import ME_One from './img/productlistbycat/me_1.png';
import ME_Two from './img/productlistbycat/me_2.png';
import ME_Three from './img/productlistbycat/me_3.png';
import ME_Four from './img/productlistbycat/me_4.png';

import MobilAccessories from './img/productlistbycat/electronic.png';
import MA_One from './img/productlistbycat/ma_1.png';
import MA_Two from './img/productlistbycat/ma_2.png';
import MA_Three from './img/productlistbycat/ma_3.png';
import MA_Four from './img/productlistbycat/ma_4.png';

import MobileFashion from './img/productlistbycat/fashion.png';
import MF_One from './img/productlistbycat/mf_1.png';
import MF_Two from './img/productlistbycat/mf_2.png';
import MF_Three from './img/productlistbycat/mf_3.png';
import MF_Four from './img/productlistbycat/mf_4.png';

import user_one from './img/user/u1.png';
import user_two from './img/user/u2.png';
import user_three from './img/user/u3.png';
import user_four from './img/user/u4.png';
import user_five from './img/user/u5.png';

import ElectCat from './img/catdetail/electronic.png';
import GroceryCat from './img/catdetail/gocery.png';
import FashCat from './img/catdetail/fashion.png';

const promotions = [
  {
    productId: 7,
    url: BsOne,
    name: 'Blueberry Cyclone',
    originalPrice: 10000,
    promotePrice: 7000,
    promotePercent: 30,
    isFav: false,
    fromPrice: 0,
    toPrice: 0,
    hasFromToPrice: false,
    promoteFromPrice: null,
    promoteToPrice: null,
    totalWishList: 0,
    totalOrder: 8,
    skuValueSize: 2,
    leftQtyForFirstSkuValue: 94,
    firstSkuValue: '3%',
    firstSkuId: 1,
    rating: 4.9,
    ratingCount: 20,
  },
  {
    productId: 9,
    url: BsTwo,
    name: 'Cokeholic',
    originalPrice: 10000,
    promotePrice: 8000,
    promotePercent: 20,
    isFav: false,
    fromPrice: 0,
    toPrice: 0,
    hasFromToPrice: false,
    promoteFromPrice: null,
    promoteToPrice: null,
    totalWishList: 0,
    totalOrder: 0,
    skuValueSize: 1,
    leftQtyForFirstSkuValue: 100,
    firstSkuValue: '5%',
    firstSkuId: 1,
    rating: 4.9,
    ratingCount: 20,
  },
  {
    productId: 14,
    url: BsOne,
    name: 'Refreshing Mint ',
    originalPrice: 10000,
    promotePrice: 8000,
    promotePercent: 20,
    isFav: false,
    fromPrice: 0,
    toPrice: 0,
    hasFromToPrice: false,
    promoteFromPrice: null,
    promoteToPrice: null,
    totalWishList: 0,
    totalOrder: 0,
    skuValueSize: 1,
    leftQtyForFirstSkuValue: 100,
    firstSkuValue: '5%',
    firstSkuId: 1,
    rating: 4.9,
    ratingCount: 20,
  },
  {
    productId: 4,
    url: BsTwo,
    name: 'Kiwi Sour',
    originalPrice: 10000,
    promotePrice: 9000,
    promotePercent: 10,
    isFav: false,
    fromPrice: 0,
    toPrice: 0,
    hasFromToPrice: false,
    promoteFromPrice: null,
    promoteToPrice: null,
    totalWishList: 0,
    totalOrder: 5,
    skuValueSize: 2,
    leftQtyForFirstSkuValue: 100,
    firstSkuValue: '3%',
    firstSkuId: 1,
    rating: 4.9,
    ratingCount: 20,
  },
  {
    productId: 5,
    url: BsOne,
    name: 'Pummelo Peel',
    originalPrice: 10000,
    promotePrice: 9000,
    promotePercent: 10,
    isFav: false,
    fromPrice: 0,
    toPrice: 0,
    hasFromToPrice: false,
    promoteFromPrice: null,
    promoteToPrice: null,
    totalWishList: 0,
    totalOrder: 0,
    skuValueSize: 1,
    leftQtyForFirstSkuValue: 100,
    firstSkuValue: '0%',
    firstSkuId: 1,
    rating: 4.9,
    ratingCount: 20,
  },
  {
    productId: 25,
    url: BsTwo,
    name: 'Cytrus Disposable',
    originalPrice: 20000,
    promotePrice: 10000,
    promotePercent: 50,
    isFav: false,
    fromPrice: 0,
    toPrice: 0,
    hasFromToPrice: false,
    promoteFromPrice: null,
    promoteToPrice: null,
    totalWishList: 0,
    totalOrder: 1,
    skuValueSize: 1,
    leftQtyForFirstSkuValue: 179,
    firstSkuValue: '5%',
    firstSkuId: 1,
    rating: 4.9,
    ratingCount: 20,
  },
  {
    productId: 26,
    url: BsOne,
    name: 'Dummy Products',
    originalPrice: 20000,
    promotePrice: 16000,
    promotePercent: 20,
    isFav: false,
    fromPrice: 0,
    toPrice: 0,
    hasFromToPrice: false,
    promoteFromPrice: null,
    promoteToPrice: null,
    totalWishList: 0,
    totalOrder: 0,
    skuValueSize: 1,
    leftQtyForFirstSkuValue: 100,
    firstSkuValue: '5%',
    firstSkuId: 1,
    rating: 4.9,
    ratingCount: 20,
  },
];
const mainCategory = [
  {
    id: 1,
    name: 'Skincare & Hair Care',
    description: 'Find the best for you here!',
    url: Health,
    backgroundUrl: null,
    subCategory: [
      {
        id: 5,
        name: 'Wild Green',
        description: null,
        url: 'https://aws-mhsimages-bucket.s3-ap-southeast-1.amazonaws.com/sit/VapePI/images/Category/2b571540-c97b-4e33-9143-5b48ca6d43af..png',
        mainCategoryId: 1,
        statusCode: 0,
        message: null,
        ref: null,
      },
      {
        id: 6,
        name: 'Sky Black',
        description: null,
        url: 'https://aws-mhsimages-bucket.s3-ap-southeast-1.amazonaws.com/sit/VapePI/images/Category/2725440d-19f9-40b5-b4d1-6bceb6b92566..png',
        mainCategoryId: 1,
        statusCode: 0,
        message: null,
        ref: null,
      },
      {
        id: 30,
        name: 'Vape Device',
        description: null,
        url: 'https://aws-mhsimages-bucket.s3-ap-southeast-1.amazonaws.com/sit/VapePI/images/Category/cafca19b-fa57-41f5-9ce7-0b9fb2449e94..png',
        mainCategoryId: 1,
        statusCode: 0,
        message: null,
        ref: null,
      },
    ],
    statusCode: 0,
    message: null,
    ref: null,
  },
  {
    id: 2,
    name: 'Electronics Devices',
    description: 'Variety of choices available',
    url: Phone,
    backgroundUrl: null,
    subCategory: [
      {
        id: 7,
        name: 'Flavors',
        description: null,
        url: 'https://aws-mhsimages-bucket.s3-ap-southeast-1.amazonaws.com/sit/VapePI/images/Category/6b393fdd-cbdb-4f91-a497-e01a3d2cb505..png',
        mainCategoryId: 2,
        statusCode: 0,
        message: null,
        ref: null,
      },
      {
        id: 8,
        name: 'Pummelo Peel',
        description: null,
        url: 'https://aws-mhsimages-bucket.s3-ap-southeast-1.amazonaws.com/sit/VapePI/images/Category/5fb5cdda-bd2d-453e-b51d-9b5775011306..png',
        mainCategoryId: 2,
        statusCode: 0,
        message: null,
        ref: null,
      },
      {
        id: 9,
        name: 'Strawberry Strike',
        description: null,
        url: 'https://aws-mhsimages-bucket.s3-ap-southeast-1.amazonaws.com/sit/VapePI/images/Category/c01e0887-d680-45de-89af-ccff1c443688..png',
        mainCategoryId: 2,
        statusCode: 0,
        message: null,
        ref: null,
      },
      {
        id: 10,
        name: 'Blueberry Cyclone',
        description: null,
        url: 'https://aws-mhsimages-bucket.s3-ap-southeast-1.amazonaws.com/sit/VapePI/images/Category/fc0f8dc8-814e-496f-8a72-60b81fc71f01..png',
        mainCategoryId: 2,
        statusCode: 0,
        message: null,
        ref: null,
      },
    ],
    statusCode: 0,
    message: null,
    ref: null,
  },
  {
    id: 3,
    name: 'Mobile Accessories',
    description: 'Easy, clean & superb flavor',
    url: AirPod,
    backgroundUrl: null,
    subCategory: [
      {
        id: 19,
        name: 'Disposable',
        description: null,
        url: 'https://aws-mhsimages-bucket.s3-ap-southeast-1.amazonaws.com/sit/VapePI/images/Category/a510b656-9e52-4105-b1dc-eb6f75eab237..png',
        mainCategoryId: 3,
        statusCode: 0,
        message: null,
        ref: null,
      },
      {
        id: 20,
        name: 'Strawberry Strike',
        description: null,
        url: 'https://aws-mhsimages-bucket.s3-ap-southeast-1.amazonaws.com/sit/VapePI/images/Category/dc29b413-4b7c-422d-abc9-4559632c94a1..png',
        mainCategoryId: 3,
        statusCode: 0,
        message: null,
        ref: null,
      },
      {
        id: 21,
        name: 'Blueberry Cyclone',
        description: null,
        url: 'https://aws-mhsimages-bucket.s3-ap-southeast-1.amazonaws.com/sit/VapePI/images/Category/25ebf46c-8499-438c-9024-7e11614982bd..png',
        mainCategoryId: 3,
        statusCode: 0,
        message: null,
        ref: null,
      },
    ],
    statusCode: 0,
    message: null,
    ref: null,
  },
  {
    id: 4,
    name: 'Fashion & Accessories',
    description: 'Easy, clean & superb flavor',
    url: Shirt,
    backgroundUrl: null,
    subCategory: [
      {
        id: 19,
        name: 'Disposable',
        description: null,
        url: 'https://aws-mhsimages-bucket.s3-ap-southeast-1.amazonaws.com/sit/VapePI/images/Category/a510b656-9e52-4105-b1dc-eb6f75eab237..png',
        mainCategoryId: 3,
        statusCode: 0,
        message: null,
        ref: null,
      },
      {
        id: 20,
        name: 'Strawberry Strike',
        description: null,
        url: 'https://aws-mhsimages-bucket.s3-ap-southeast-1.amazonaws.com/sit/VapePI/images/Category/dc29b413-4b7c-422d-abc9-4559632c94a1..png',
        mainCategoryId: 3,
        statusCode: 0,
        message: null,
        ref: null,
      },
      {
        id: 21,
        name: 'Blueberry Cyclone',
        description: null,
        url: 'https://aws-mhsimages-bucket.s3-ap-southeast-1.amazonaws.com/sit/VapePI/images/Category/25ebf46c-8499-438c-9024-7e11614982bd..png',
        mainCategoryId: 3,
        statusCode: 0,
        message: null,
        ref: null,
      },
    ],
    statusCode: 0,
    message: null,
    ref: null,
  },
  {
    id: 5,
    name: 'Food & Grocery',
    description: 'Easy, clean & superb flavor',
    url: Phone,
    backgroundUrl: null,
    subCategory: [
      {
        id: 19,
        name: 'Disposable',
        description: null,
        url: 'https://aws-mhsimages-bucket.s3-ap-southeast-1.amazonaws.com/sit/VapePI/images/Category/a510b656-9e52-4105-b1dc-eb6f75eab237..png',
        mainCategoryId: 3,
        statusCode: 0,
        message: null,
        ref: null,
      },
      {
        id: 20,
        name: 'Strawberry Strike',
        description: null,
        url: 'https://aws-mhsimages-bucket.s3-ap-southeast-1.amazonaws.com/sit/VapePI/images/Category/dc29b413-4b7c-422d-abc9-4559632c94a1..png',
        mainCategoryId: 3,
        statusCode: 0,
        message: null,
        ref: null,
      },
      {
        id: 21,
        name: 'Blueberry Cyclone',
        description: null,
        url: 'https://aws-mhsimages-bucket.s3-ap-southeast-1.amazonaws.com/sit/VapePI/images/Category/25ebf46c-8499-438c-9024-7e11614982bd..png',
        mainCategoryId: 3,
        statusCode: 0,
        message: null,
        ref: null,
      },
    ],
    statusCode: 0,
    message: null,
    ref: null,
  },
  {
    id: 6,
    name: 'Monitor & PC Parts',
    description: 'Easy, clean & superb flavor',
    url: Phone,
    backgroundUrl: null,
    subCategory: [
      {
        id: 19,
        name: 'Disposable',
        description: null,
        url: 'https://aws-mhsimages-bucket.s3-ap-southeast-1.amazonaws.com/sit/VapePI/images/Category/a510b656-9e52-4105-b1dc-eb6f75eab237..png',
        mainCategoryId: 3,
        statusCode: 0,
        message: null,
        ref: null,
      },
      {
        id: 20,
        name: 'Strawberry Strike',
        description: null,
        url: 'https://aws-mhsimages-bucket.s3-ap-southeast-1.amazonaws.com/sit/VapePI/images/Category/dc29b413-4b7c-422d-abc9-4559632c94a1..png',
        mainCategoryId: 3,
        statusCode: 0,
        message: null,
        ref: null,
      },
      {
        id: 21,
        name: 'Blueberry Cyclone',
        description: null,
        url: 'https://aws-mhsimages-bucket.s3-ap-southeast-1.amazonaws.com/sit/VapePI/images/Category/25ebf46c-8499-438c-9024-7e11614982bd..png',
        mainCategoryId: 3,
        statusCode: 0,
        message: null,
        ref: null,
      },
    ],
    statusCode: 0,
    message: null,
    ref: null,
  },
];

const latestProduct = [
  {
    productId: 43,
    url: LatesOne,
    name: 'Denim Jean Jacket for Men',
    originalPrice: 30000,
    promotePrice: null,
    promotePercent: 10,
    createdDate: '2023-03-15T15:11:46.8322667',
    isFav: false,
    isGetOne: false,
    fromPrice: 0,
    toPrice: 0,
    hasFromToPrice: false,
    promoteFromPrice: null,
    promoteToPrice: null,
    totalWishList: 0,
    totalOrder: 0,
    skuValueSize: 1,
    leftQtyForFirstSkuValue: 100,
    firstSkuValue: 'Default',
    firstSkuId: 1,
  },
  {
    productId: 42,
    url: LatesTow,
    name: 'Denim Jean Jacket for Men',
    originalPrice: 30000,
    promotePrice: null,
    promotePercent: 0,
    createdDate: '2023-03-15T15:10:59.807325',
    isFav: false,
    isGetOne: false,
    fromPrice: 0,
    toPrice: 0,
    hasFromToPrice: false,
    promoteFromPrice: null,
    promoteToPrice: null,
    totalWishList: 0,
    totalOrder: 1,
    skuValueSize: 1,
    leftQtyForFirstSkuValue: 100,
    firstSkuValue: 'Default',
    firstSkuId: 1,
  },
  {
    productId: 41,
    url: LatesThree,
    name: 'Denim Jean Jacket for Men',
    originalPrice: 30000,
    promotePrice: null,
    promotePercent: 0,
    createdDate: '2023-03-15T15:08:31.6864097',
    isFav: false,
    isGetOne: false,
    fromPrice: 0,
    toPrice: 0,
    hasFromToPrice: false,
    promoteFromPrice: null,
    promoteToPrice: null,
    totalWishList: 0,
    totalOrder: 0,
    skuValueSize: 1,
    leftQtyForFirstSkuValue: 100,
    firstSkuValue: 'Default',
    firstSkuId: 1,
  },
  {
    productId: 40,
    url: LatesFour,
    name: 'Denim Jean Jacket for Men',
    originalPrice: 15000,
    promotePrice: null,
    promotePercent: 0,
    createdDate: '2023-03-15T15:04:42.7364571',
    isFav: false,
    isGetOne: false,
    fromPrice: 0,
    toPrice: 0,
    hasFromToPrice: false,
    promoteFromPrice: null,
    promoteToPrice: null,
    totalWishList: 0,
    totalOrder: 0,
    skuValueSize: 1,
    leftQtyForFirstSkuValue: 100,
    firstSkuValue: 'Default',
    firstSkuId: 1,
  },
  {
    productId: 39,
    url: LatesFive,
    name: 'Denim Jean Jacket for Men',
    originalPrice: 30000,
    promotePrice: null,
    promotePercent: 0,
    createdDate: '2023-03-15T15:02:17.4826393',
    isFav: false,
    isGetOne: false,
    fromPrice: 0,
    toPrice: 0,
    hasFromToPrice: false,
    promoteFromPrice: null,
    promoteToPrice: null,
    totalWishList: 0,
    totalOrder: 0,
    skuValueSize: 1,
    leftQtyForFirstSkuValue: 100,
    firstSkuValue: 'Default',
    firstSkuId: 1,
  },
  {
    productId: 38,
    url: LatesSix,
    name: 'Denim Jean Jacket for Men',
    originalPrice: 30000,
    promotePrice: null,
    promotePercent: 0,
    createdDate: '2023-03-15T14:59:54.020736',
    isFav: false,
    isGetOne: false,
    fromPrice: 0,
    toPrice: 0,
    hasFromToPrice: false,
    promoteFromPrice: null,
    promoteToPrice: null,
    totalWishList: 0,
    totalOrder: 0,
    skuValueSize: 1,
    leftQtyForFirstSkuValue: 100,
    firstSkuValue: 'Default',
    firstSkuId: 1,
  },
  {
    productId: 34,
    url: LatesOne,
    name: 'Denim Jean Jacket for Men',
    originalPrice: 30000,
    promotePrice: null,
    promotePercent: 0,
    createdDate: '2023-03-15T14:38:45.4130199',
    isFav: false,
    isGetOne: false,
    fromPrice: 0,
    toPrice: 0,
    hasFromToPrice: false,
    promoteFromPrice: null,
    promoteToPrice: null,
    totalWishList: 0,
    totalOrder: 0,
    skuValueSize: 1,
    leftQtyForFirstSkuValue: 100,
    firstSkuValue: 'Default',
    firstSkuId: 1,
  },
];

const getAllProductListsBuyer = {
  mainCategory: [
    {
      id: 1,
      name: 'Skincare & Hair Care',
      url: Health,
      webBgUrl:
        'https://aws-mhsimages-bucket.s3.ap-southeast-1.amazonaws.com/sit/VapePI/images/Category/device_web.png',
      mobileBgUrl: MobileHealthBg,
      mainCategoryId: 1,
      isCustomCategory: false,
      productListBuyers: [
        {
          productId: 40,
          productTypeId: 1,
          url: Mh_One,
          name: 'Dummy Product With Dummy',
          originalPrice: 15000,
          promotePrice: 0,
          promotePercent: 0,
          isFav: false,
          isGetOne: false,
          createdDate: '2023-03-15T15:04:42.7364571',
          fromPrice: 0,
          toPrice: 0,
          hasFromToPrice: false,
          promoteFromPrice: null,
          promoteToPrice: null,
          totalWishList: 0,
          totalOrder: 0,
          skuValueSize: 1,
          leftQtyForFirstSkuValue: 100,
          firstSkuValue: 'Default',
          firstSkuId: 1,
        },
        {
          productId: 39,
          productTypeId: 1,
          url: Mh_Two,
          name: 'Dummy Product With Dummy',
          originalPrice: 30000,
          promotePrice: 0,
          promotePercent: 0,
          isFav: false,
          isGetOne: false,
          createdDate: '2023-03-15T15:02:17.4826393',
          fromPrice: 0,
          toPrice: 0,
          hasFromToPrice: false,
          promoteFromPrice: null,
          promoteToPrice: null,
          totalWishList: 0,
          totalOrder: 0,
          skuValueSize: 1,
          leftQtyForFirstSkuValue: 100,
          firstSkuValue: 'Default',
          firstSkuId: 1,
        },
        {
          productId: 38,
          productTypeId: 1,
          url: Mh_Three,
          name: 'Dummy Product With Dummy',
          originalPrice: 30000,
          promotePrice: 0,
          promotePercent: 0,
          isFav: false,
          isGetOne: false,
          createdDate: '2023-03-15T14:59:54.020736',
          fromPrice: 0,
          toPrice: 0,
          hasFromToPrice: false,
          promoteFromPrice: null,
          promoteToPrice: null,
          totalWishList: 0,
          totalOrder: 0,
          skuValueSize: 1,
          leftQtyForFirstSkuValue: 100,
          firstSkuValue: 'Default',
          firstSkuId: 1,
        },
        {
          productId: 34,
          productTypeId: 1,
          url: Mh_Four,
          name: 'Wild Green Dummy Device',
          originalPrice: 30000,
          promotePrice: 0,
          promotePercent: 0,
          isFav: false,
          isGetOne: false,
          createdDate: '2023-03-15T14:38:45.4130199',
          fromPrice: 0,
          toPrice: 0,
          hasFromToPrice: false,
          promoteFromPrice: null,
          promoteToPrice: null,
          totalWishList: 0,
          totalOrder: 0,
          skuValueSize: 1,
          leftQtyForFirstSkuValue: 100,
          firstSkuValue: 'Default',
          firstSkuId: 1,
        },
        {
          productId: 33,
          productTypeId: 1,
          url: Mh_Four,
          name: 'Sky Black Dummy Device',
          originalPrice: 30000,
          promotePrice: 0,
          promotePercent: 0,
          isFav: false,
          isGetOne: false,
          createdDate: '2023-03-15T14:36:33.5214051',
          fromPrice: 0,
          toPrice: 0,
          hasFromToPrice: false,
          promoteFromPrice: null,
          promoteToPrice: null,
          totalWishList: 0,
          totalOrder: 0,
          skuValueSize: 1,
          leftQtyForFirstSkuValue: 100,
          firstSkuValue: 'Default',
          firstSkuId: 1,
        },
        {
          productId: 32,
          productTypeId: 1,
          url: Mh_Four,
          name: 'Cloud White Dummy Device',
          originalPrice: 30000,
          promotePrice: 0,
          promotePercent: 0,
          isFav: false,
          isGetOne: false,
          createdDate: '2023-03-15T14:34:12.6435597',
          fromPrice: 0,
          toPrice: 0,
          hasFromToPrice: false,
          promoteFromPrice: null,
          promoteToPrice: null,
          totalWishList: 0,
          totalOrder: 0,
          skuValueSize: 1,
          leftQtyForFirstSkuValue: 100,
          firstSkuValue: 'Default',
          firstSkuId: 1,
        },
        {
          productId: 31,
          productTypeId: 1,
          url: Mh_Four,
          name: 'Cloud White Dummy Device',
          originalPrice: 30000,
          promotePrice: 0,
          promotePercent: 0,
          isFav: false,
          isGetOne: true,
          createdDate: '2023-03-15T14:01:22.7845282',
          fromPrice: 0,
          toPrice: 0,
          hasFromToPrice: false,
          promoteFromPrice: null,
          promoteToPrice: null,
          totalWishList: 0,
          totalOrder: 0,
          skuValueSize: 1,
          leftQtyForFirstSkuValue: 100,
          firstSkuValue: 'Default',
          firstSkuId: 1,
        },
      ],
    },
    {
      id: 2,
      name: 'Electronic Devices',
      url: Phone,
      webBgUrl:
        'https://aws-mhsimages-bucket.s3.ap-southeast-1.amazonaws.com/sit/VapePI/images/Category/pods_web.png',
      mobileBgUrl: MobilePhoneBg,
      mainCategoryId: 2,
      isCustomCategory: false,
      productListBuyers: [
        {
          productId: 16,
          productTypeId: 1,
          url: ME_One,
          name: 'Lemongrass with Dummy Herb',
          originalPrice: 10000,
          promotePrice: 0,
          promotePercent: 0,
          isFav: false,
          isGetOne: true,
          createdDate: '2023-03-14T12:09:33.068374',
          fromPrice: 0,
          toPrice: 0,
          hasFromToPrice: false,
          promoteFromPrice: null,
          promoteToPrice: null,
          totalWishList: 0,
          totalOrder: 0,
          skuValueSize: 1,
          leftQtyForFirstSkuValue: 100,
          firstSkuValue: '3%',
          firstSkuId: 1,
        },
        {
          productId: 15,
          productTypeId: 1,
          url: ME_Two,
          name: 'Sanqi with Dummy Power',
          originalPrice: 10000,
          promotePrice: 0,
          promotePercent: 0,
          isFav: false,
          isGetOne: false,
          createdDate: '2023-03-14T12:07:47.9013508',
          fromPrice: 0,
          toPrice: 0,
          hasFromToPrice: false,
          promoteFromPrice: null,
          promoteToPrice: null,
          totalWishList: 0,
          totalOrder: 5,
          skuValueSize: 1,
          leftQtyForFirstSkuValue: 95,
          firstSkuValue: '0%',
          firstSkuId: 1,
        },
        {
          productId: 14,
          productTypeId: 1,
          url: ME_Three,
          name: 'Refreshing with Dummy Mint ',
          originalPrice: 10000,
          promotePrice: 8000,
          promotePercent: 20,
          isFav: false,
          isGetOne: false,
          createdDate: '2023-03-14T11:52:17.394545',
          fromPrice: 0,
          toPrice: 0,
          hasFromToPrice: false,
          promoteFromPrice: null,
          promoteToPrice: null,
          totalWishList: 0,
          totalOrder: 0,
          skuValueSize: 1,
          leftQtyForFirstSkuValue: 100,
          firstSkuValue: '5%',
          firstSkuId: 1,
        },
        {
          productId: 12,
          productTypeId: 1,
          url: ME_Four,
          name: 'Cytrus with Dummy Monster',
          originalPrice: 10000,
          promotePrice: 0,
          promotePercent: 0,
          isFav: false,
          isGetOne: false,
          createdDate: '2023-03-14T11:51:11.0568423',
          fromPrice: 0,
          toPrice: 0,
          hasFromToPrice: false,
          promoteFromPrice: null,
          promoteToPrice: null,
          totalWishList: 0,
          totalOrder: 0,
          skuValueSize: 1,
          leftQtyForFirstSkuValue: 100,
          firstSkuValue: '5%',
          firstSkuId: 1,
        },
        {
          productId: 18,
          productTypeId: 1,
          url: ME_Four,
          name: 'Lychee With Dummy Rose',
          originalPrice: 10000,
          promotePrice: 0,
          promotePercent: 0,
          isFav: false,
          isGetOne: true,
          createdDate: '2023-03-14T11:49:51.7987656',
          fromPrice: 0,
          toPrice: 0,
          hasFromToPrice: false,
          promoteFromPrice: null,
          promoteToPrice: null,
          totalWishList: 0,
          totalOrder: 6,
          skuValueSize: 1,
          leftQtyForFirstSkuValue: 94,
          firstSkuValue: '5%',
          firstSkuId: 1,
        },
        {
          productId: 11,
          productTypeId: 1,
          url: ME_Four,
          name: 'Lychee With Dummy Rose',
          originalPrice: 10000,
          promotePrice: 0,
          promotePercent: 0,
          isFav: false,
          isGetOne: true,
          createdDate: '2023-03-14T11:49:51.7987656',
          fromPrice: 0,
          toPrice: 0,
          hasFromToPrice: false,
          promoteFromPrice: null,
          promoteToPrice: null,
          totalWishList: 0,
          totalOrder: 6,
          skuValueSize: 1,
          leftQtyForFirstSkuValue: 94,
          firstSkuValue: '5%',
          firstSkuId: 1,
        },
        {
          productId: 10,
          productTypeId: 1,
          url: ME_Four,
          name: 'Lychee With Dummy Rose',
          originalPrice: 10000,
          promotePrice: 0,
          promotePercent: 0,
          isFav: false,
          isGetOne: true,
          createdDate: '2023-03-14T11:49:51.7987656',
          fromPrice: 0,
          toPrice: 0,
          hasFromToPrice: false,
          promoteFromPrice: null,
          promoteToPrice: null,
          totalWishList: 0,
          totalOrder: 6,
          skuValueSize: 1,
          leftQtyForFirstSkuValue: 94,
          firstSkuValue: '5%',
          firstSkuId: 1,
        },
      ],
    },
    {
      id: 3,
      name: 'Mobile Accessories',
      url: AirPod,
      webBgUrl:
        'https://aws-mhsimages-bucket.s3.ap-southeast-1.amazonaws.com/sit/VapePI/images/Category/disposable_web.png',
      mobileBgUrl: MobilAccessories,
      mainCategoryId: 3,
      isCustomCategory: false,
      productListBuyers: [
        {
          productId: 7,
          productTypeId: 1,
          url: MA_One,
          name: 'Cytrus Monster Disposable Pod',
          originalPrice: 20000,
          promotePrice: 0,
          promotePercent: 0,
          isFav: false,
          isGetOne: false,
          createdDate: '2023-03-15T10:15:13.3871477',
          fromPrice: 0,
          toPrice: 0,
          hasFromToPrice: false,
          promoteFromPrice: null,
          promoteToPrice: null,
          totalWishList: 0,
          totalOrder: 0,
          skuValueSize: 1,
          leftQtyForFirstSkuValue: 100,
          firstSkuValue: '5%',
          firstSkuId: 1,
        },
        {
          productId: 26,
          productTypeId: 1,
          url: MA_Two,
          name: 'Refreshing Mint Disposable ',
          originalPrice: 20000,
          promotePrice: 16000,
          promotePercent: 20,
          isFav: false,
          isGetOne: false,
          createdDate: '2023-03-14T12:41:14.9263005',
          fromPrice: 0,
          toPrice: 0,
          hasFromToPrice: false,
          promoteFromPrice: null,
          promoteToPrice: null,
          totalWishList: 0,
          totalOrder: 0,
          skuValueSize: 1,
          leftQtyForFirstSkuValue: 100,
          firstSkuValue: '5%',
          firstSkuId: 1,
        },
        {
          productId: 25,
          productTypeId: 1,
          url: MA_Three,
          name: 'Cytrus Monster Disposable',
          originalPrice: 20000,
          promotePrice: 10000,
          promotePercent: 50,
          isFav: false,
          isGetOne: false,
          createdDate: '2023-03-14T12:40:10.483589',
          fromPrice: 0,
          toPrice: 0,
          hasFromToPrice: false,
          promoteFromPrice: null,
          promoteToPrice: null,
          totalWishList: 0,
          totalOrder: 1,
          skuValueSize: 1,
          leftQtyForFirstSkuValue: 179,
          firstSkuValue: '5%',
          firstSkuId: 1,
        },
        {
          productId: 24,
          productTypeId: 1,
          url: MA_Four,
          name: 'Lychee Rose Dummy Disposable',
          originalPrice: 20000,
          promotePrice: 0,
          promotePercent: 0,
          isFav: false,
          isGetOne: true,
          createdDate: '2023-03-14T12:38:10.3297377',
          fromPrice: 0,
          toPrice: 0,
          hasFromToPrice: false,
          promoteFromPrice: null,
          promoteToPrice: null,
          totalWishList: 1,
          totalOrder: 0,
          skuValueSize: 1,
          leftQtyForFirstSkuValue: 100,
          firstSkuValue: '5%',
          firstSkuId: 1,
        },
        {
          productId: 23,
          productTypeId: 1,
          url: MA_Four,
          name: 'Lychee Rose Dummy Disposable',
          originalPrice: 20000,
          promotePrice: 0,
          promotePercent: 0,
          isFav: false,
          isGetOne: true,
          createdDate: '2023-03-14T12:38:10.3297377',
          fromPrice: 0,
          toPrice: 0,
          hasFromToPrice: false,
          promoteFromPrice: null,
          promoteToPrice: null,
          totalWishList: 1,
          totalOrder: 0,
          skuValueSize: 1,
          leftQtyForFirstSkuValue: 100,
          firstSkuValue: '5%',
          firstSkuId: 1,
        },
        {
          productId: 22,
          productTypeId: 1,
          url: MA_Four,
          name: 'Lychee Rose Dummy Disposable',
          originalPrice: 20000,
          promotePrice: 0,
          promotePercent: 0,
          isFav: false,
          isGetOne: true,
          createdDate: '2023-03-14T12:38:10.3297377',
          fromPrice: 0,
          toPrice: 0,
          hasFromToPrice: false,
          promoteFromPrice: null,
          promoteToPrice: null,
          totalWishList: 1,
          totalOrder: 0,
          skuValueSize: 1,
          leftQtyForFirstSkuValue: 100,
          firstSkuValue: '5%',
          firstSkuId: 1,
        },
        {
          productId: 21,
          productTypeId: 1,
          url: MA_Four,
          name: 'Lychee Rose Dummy Disposable',
          originalPrice: 20000,
          promotePrice: 0,
          promotePercent: 0,
          isFav: false,
          isGetOne: true,
          createdDate: '2023-03-14T12:38:10.3297377',
          fromPrice: 0,
          toPrice: 0,
          hasFromToPrice: false,
          promoteFromPrice: null,
          promoteToPrice: null,
          totalWishList: 1,
          totalOrder: 0,
          skuValueSize: 1,
          leftQtyForFirstSkuValue: 100,
          firstSkuValue: '5%',
          firstSkuId: 1,
        },
      ],
    },
    {
      id: 4,
      name: 'Fashion  & Accessories',
      url: Shirt,
      webBgUrl:
        'https://aws-mhsimages-bucket.s3.ap-southeast-1.amazonaws.com/sit/VapePI/images/Category/disposable_web.png',
      mobileBgUrl: MobileFashion,
      mainCategoryId: 3,
      isCustomCategory: false,
      productListBuyers: [
        {
          productId: 28,
          productTypeId: 1,
          url: MF_One,
          name: 'Cytrus Monster Disposable Pod',
          originalPrice: 20000,
          promotePrice: 0,
          promotePercent: 0,
          isFav: false,
          isGetOne: false,
          createdDate: '2023-03-15T10:15:13.3871477',
          fromPrice: 0,
          toPrice: 0,
          hasFromToPrice: false,
          promoteFromPrice: null,
          promoteToPrice: null,
          totalWishList: 0,
          totalOrder: 0,
          skuValueSize: 1,
          leftQtyForFirstSkuValue: 100,
          firstSkuValue: '5%',
          firstSkuId: 1,
        },
        {
          productId: 26,
          productTypeId: 1,
          url: MF_Two,
          name: 'Refreshing Mint Disposable ',
          originalPrice: 20000,
          promotePrice: 16000,
          promotePercent: 20,
          isFav: false,
          isGetOne: false,
          createdDate: '2023-03-14T12:41:14.9263005',
          fromPrice: 0,
          toPrice: 0,
          hasFromToPrice: false,
          promoteFromPrice: null,
          promoteToPrice: null,
          totalWishList: 0,
          totalOrder: 0,
          skuValueSize: 1,
          leftQtyForFirstSkuValue: 100,
          firstSkuValue: '5%',
          firstSkuId: 1,
        },
        {
          productId: 25,
          productTypeId: 1,
          url: MF_Three,
          name: 'Cytrus Monster Disposable',
          originalPrice: 20000,
          promotePrice: 10000,
          promotePercent: 50,
          isFav: false,
          isGetOne: false,
          createdDate: '2023-03-14T12:40:10.483589',
          fromPrice: 0,
          toPrice: 0,
          hasFromToPrice: false,
          promoteFromPrice: null,
          promoteToPrice: null,
          totalWishList: 0,
          totalOrder: 1,
          skuValueSize: 1,
          leftQtyForFirstSkuValue: 179,
          firstSkuValue: '5%',
          firstSkuId: 1,
        },
        {
          productId: 24,
          productTypeId: 1,
          url: MF_Four,
          name: 'Lychee Rose Dummy Disposable',
          originalPrice: 20000,
          promotePrice: 0,
          promotePercent: 0,
          isFav: false,
          isGetOne: true,
          createdDate: '2023-03-14T12:38:10.3297377',
          fromPrice: 0,
          toPrice: 0,
          hasFromToPrice: false,
          promoteFromPrice: null,
          promoteToPrice: null,
          totalWishList: 1,
          totalOrder: 0,
          skuValueSize: 1,
          leftQtyForFirstSkuValue: 100,
          firstSkuValue: '5%',
          firstSkuId: 1,
        },
        {
          productId: 23,
          productTypeId: 1,
          url: MF_Four,
          name: 'Lychee Rose Dummy Disposable',
          originalPrice: 20000,
          promotePrice: 0,
          promotePercent: 0,
          isFav: false,
          isGetOne: true,
          createdDate: '2023-03-14T12:38:10.3297377',
          fromPrice: 0,
          toPrice: 0,
          hasFromToPrice: false,
          promoteFromPrice: null,
          promoteToPrice: null,
          totalWishList: 1,
          totalOrder: 0,
          skuValueSize: 1,
          leftQtyForFirstSkuValue: 100,
          firstSkuValue: '5%',
          firstSkuId: 1,
        },
        {
          productId: 55,
          productTypeId: 1,
          url: MF_Four,
          name: 'Lychee Rose Dummy Disposable',
          originalPrice: 20000,
          promotePrice: 0,
          promotePercent: 0,
          isFav: false,
          isGetOne: true,
          createdDate: '2023-03-14T12:38:10.3297377',
          fromPrice: 0,
          toPrice: 0,
          hasFromToPrice: false,
          promoteFromPrice: null,
          promoteToPrice: null,
          totalWishList: 1,
          totalOrder: 0,
          skuValueSize: 1,
          leftQtyForFirstSkuValue: 100,
          firstSkuValue: '5%',
          firstSkuId: 1,
        },
        {
          productId: 26,
          productTypeId: 1,
          url: MF_Four,
          name: 'Lychee Rose Dummy Disposable',
          originalPrice: 20000,
          promotePrice: 0,
          promotePercent: 0,
          isFav: false,
          isGetOne: true,
          createdDate: '2023-03-14T12:38:10.3297377',
          fromPrice: 0,
          toPrice: 0,
          hasFromToPrice: false,
          promoteFromPrice: null,
          promoteToPrice: null,
          totalWishList: 1,
          totalOrder: 0,
          skuValueSize: 1,
          leftQtyForFirstSkuValue: 100,
          firstSkuValue: '5%',
          firstSkuId: 1,
        },
      ],
    },
  ],
};

const buyOneGetOne = [
  {
    productId: 8,
    url: 'https://aws-mhsimages-bucket.s3-ap-southeast-1.amazonaws.com/sit/VapePI/images/product/481b6b9b-083c-43f8-81e6-e9f68cd46456..png',
    name: 'Clove Aroma',
    originalPrice: 10000,
    isFav: false,
    isGetOne: true,
    fromPrice: 0,
    toPrice: 0,
    hasFromToPrice: false,
    promoteFromPrice: null,
    promoteToPrice: null,
    totalWishList: 0,
    totalOrder: 0,
    skuValueSize: 2,
    leftQtyForFirstSkuValue: 100,
    firstSkuValue: '3%',
    firstSkuId: 1,
  },
  {
    productId: 11,
    url: 'https://aws-mhsimages-bucket.s3-ap-southeast-1.amazonaws.com/sit/VapePI/images/product/354d5242-1610-4f17-8d46-8e53bc730107..png',
    name: 'Lychee Rose',
    originalPrice: 10000,
    isFav: false,
    isGetOne: true,
    fromPrice: 0,
    toPrice: 0,
    hasFromToPrice: false,
    promoteFromPrice: null,
    promoteToPrice: null,
    totalWishList: 0,
    totalOrder: 0,
    skuValueSize: 1,
    leftQtyForFirstSkuValue: 94,
    firstSkuValue: '5%',
    firstSkuId: 1,
  },
  {
    productId: 16,
    url: 'https://aws-mhsimages-bucket.s3-ap-southeast-1.amazonaws.com/sit/VapePI/images/product/2bb479cc-5f77-44ed-a869-1c492806c45d..png',
    name: 'Lemongrass Herb',
    originalPrice: 10000,
    isFav: false,
    isGetOne: true,
    fromPrice: 0,
    toPrice: 0,
    hasFromToPrice: false,
    promoteFromPrice: null,
    promoteToPrice: null,
    totalWishList: 0,
    totalOrder: 0,
    skuValueSize: 1,
    leftQtyForFirstSkuValue: 100,
    firstSkuValue: '3%',
    firstSkuId: 1,
  },
  {
    productId: 17,
    url: 'https://aws-mhsimages-bucket.s3-ap-southeast-1.amazonaws.com/sit/VapePI/images/product/d71049b6-65e3-4d37-8849-135da054065f..png',
    name: 'Kiwi Sour Disposable ',
    originalPrice: 20000,
    isFav: false,
    isGetOne: true,
    fromPrice: 0,
    toPrice: 0,
    hasFromToPrice: false,
    promoteFromPrice: null,
    promoteToPrice: null,
    totalWishList: 0,
    totalOrder: 0,
    skuValueSize: 2,
    leftQtyForFirstSkuValue: 100,
    firstSkuValue: '3%',
    firstSkuId: 1,
  },
  {
    productId: 20,
    url: 'https://aws-mhsimages-bucket.s3-ap-southeast-1.amazonaws.com/sit/VapePI/images/product/a6304d4e-6bc6-4f28-a479-70786080a383..png',
    name: 'Pineapple Splash Disposable',
    originalPrice: 20000,
    isFav: false,
    isGetOne: true,
    fromPrice: 0,
    toPrice: 0,
    hasFromToPrice: false,
    promoteFromPrice: null,
    promoteToPrice: null,
    totalWishList: 0,
    totalOrder: 0,
    skuValueSize: 2,
    leftQtyForFirstSkuValue: 100,
    firstSkuValue: '3%',
    firstSkuId: 1,
  },
  {
    productId: 24,
    url: 'https://aws-mhsimages-bucket.s3-ap-southeast-1.amazonaws.com/sit/VapePI/images/product/6fd33a4f-1a70-44d8-8a50-1e4cd98aae37..png',
    name: 'Lychee Rose Disposable',
    originalPrice: 20000,
    isFav: false,
    isGetOne: true,
    fromPrice: 0,
    toPrice: 0,
    hasFromToPrice: false,
    promoteFromPrice: null,
    promoteToPrice: null,
    totalWishList: 0,
    totalOrder: 0,
    skuValueSize: 1,
    leftQtyForFirstSkuValue: 100,
    firstSkuValue: '5%',
    firstSkuId: 1,
  },
  {
    productId: 31,
    url: 'https://aws-mhsimages-bucket.s3-ap-southeast-1.amazonaws.com/sit/VapePI/images/product/7ff21311-a766-4b3b-8e24-9c3fefede1a4..png',
    name: 'Cloud White Pod Device',
    originalPrice: 30000,
    isFav: false,
    isGetOne: true,
    fromPrice: 0,
    toPrice: 0,
    hasFromToPrice: false,
    promoteFromPrice: null,
    promoteToPrice: null,
    totalWishList: 0,
    totalOrder: 0,
    skuValueSize: 1,
    leftQtyForFirstSkuValue: 100,
    firstSkuValue: 'Default',
    firstSkuId: 1,
  },
];

const reward = {
  productRewardList: [
    {
      productId: 6,
      name: 'Strawberry Strike',
      point: 100,
      expiredDate: '2023-03-31T23:59:59.455',
      isForSale: true,
      isFreeDelivery: false,
      productImgUrl:
        'https://aws-mhsimages-bucket.s3-ap-southeast-1.amazonaws.com/sit/VapePI/images/product/97ee6996-4e1e-4ca6-9879-1d45f6638832..png',
    },
    {
      productId: 29,
      name: 'Wild Green Pod Device',
      point: 500,
      expiredDate: '2023-04-30T13:52:29.502',
      isForSale: true,
      isFreeDelivery: false,
      productImgUrl:
        'https://aws-mhsimages-bucket.s3-ap-southeast-1.amazonaws.com/sit/VapePI/images/product/5e4ebce0-cd41-4d04-9f64-633e1326c2e9..png',
    },
    {
      productId: 68,
      name: 'Cytrus Monster Disposable Pod',
      point: 1000,
      expiredDate: '2023-04-28T23:59:59.455',
      isForSale: true,
      isFreeDelivery: false,
      productImgUrl:
        'https://aws-mhsimages-bucket.s3-ap-southeast-1.amazonaws.com/sit/VapePI/images/product/2731001a-5c55-43b1-b694-bd71525121ba..png',
    },
    {
      productId: 34,
      name: 'Wild Green Vape Device',
      point: 400,
      expiredDate: '2023-04-30T14:40:09.395',
      isForSale: true,
      isFreeDelivery: false,
      productImgUrl:
        'https://aws-mhsimages-bucket.s3-ap-southeast-1.amazonaws.com/sit/VapePI/images/product/d763262b-0d3b-46f1-b574-80980a7621be..png',
    },
    {
      productId: 33,
      name: 'Sky Black Vape Device',
      point: 500,
      expiredDate: '2023-04-30T14:37:21.265',
      isForSale: true,
      isFreeDelivery: false,
      productImgUrl:
        'https://aws-mhsimages-bucket.s3-ap-southeast-1.amazonaws.com/sit/VapePI/images/product/b3e026ea-63ff-4308-8ea6-8fa12656e037..png',
    },
    {
      productId: 32,
      name: 'Cloud White Vape Device',
      point: 300,
      expiredDate: '2023-03-31T14:34:41.361',
      isForSale: true,
      isFreeDelivery: false,
      productImgUrl:
        'https://aws-mhsimages-bucket.s3-ap-southeast-1.amazonaws.com/sit/VapePI/images/product/c27bb8d2-c36c-4b7d-aa86-9338fa5745b0..png',
    },
    {
      productId: 38,
      name: 'Wild Green Pod',
      point: 500,
      expiredDate: '2023-04-30T15:00:19.091',
      isForSale: true,
      isFreeDelivery: false,
      productImgUrl:
        'https://aws-mhsimages-bucket.s3-ap-southeast-1.amazonaws.com/sit/VapePI/images/product/88d15cf9-e963-4e22-ba31-02f83fdb332d..png',
    },
  ],
  total_Pages: 1,
  total_Results: 7,
  statusCode: 0,
  message: null,
  ref: null,
};

const recommend = {
  recommendedTitle: 'Thingyan Sales',
  recommendedList: [
    {
      id: 1,
      title: 'အမိုက်စား POD များ',
      thumbnailUrlMobile:
        'https://aws-mhsimages-bucket.s3-ap-southeast-1.amazonaws.com/sit/VapePI/images/recommended/0ac1c820-8483-4f3f-9027-6a3cdaaf12b5..png',
      thumbnailUrlWeb:
        'https://aws-mhsimages-bucket.s3-ap-southeast-1.amazonaws.com/sit/VapePI/images/recommended/866cffae-46d4-46b8-8cbf-885114c4c6dc..png',
      productCount: 3,
      brandCount: 0,
    },
    {
      id: 2,
      title: 'အလန်းစား Pod များ',
      thumbnailUrlMobile:
        'https://aws-mhsimages-bucket.s3-ap-southeast-1.amazonaws.com/sit/VapePI/images/recommended/c30d454f-a937-46a0-940e-7eacc81ea8ec..png',
      thumbnailUrlWeb:
        'https://aws-mhsimages-bucket.s3-ap-southeast-1.amazonaws.com/sit/VapePI/images/recommended/f46d03c9-3750-49fe-affa-9fa4f4a8eb75..png',
      productCount: 3,
      brandCount: 0,
    },
  ],
};
const banner = [
  {
    id: 201,
    name: 'MobileBanner3',
    url: MobileBanner,
    bannerLinkId: 7,
    isWeb: 0,
    brandId: null,
    seqNo: 3,
    width: '1074',
    height: '1440',
    categoryId: null,
    categoryName: null,
    categoryImgUrl: null,
    productId: null,
    productName: null,
    searchKeyword: null,
    recommendedId: null,
  },
  {
    id: 202,
    name: 'MobileBanner2',
    url: MobileBanner,
    bannerLinkId: 15,
    isWeb: 0,
    brandId: null,
    seqNo: 2,
    width: '1074',
    height: '1440',
    categoryId: null,
    categoryName: null,
    categoryImgUrl: null,
    productId: null,
    productName: null,
    searchKeyword: null,
    recommendedId: null,
  },
  {
    id: 203,
    name: 'MobileBanner1',
    url: MobileBanner,
    bannerLinkId: 9,
    isWeb: 0,
    brandId: null,
    seqNo: 1,
    width: '1074',
    height: '1440',
    categoryId: null,
    categoryName: null,
    categoryImgUrl: null,
    productId: null,
    productName: null,
    searchKeyword: 'pods',
    recommendedId: null,
  },
  {
    id: 216,
    name: 'WebBanner1',
    url: 'https://aws-mhsimages-bucket.s3-ap-southeast-1.amazonaws.com/sit/VapePI/images/product/af01197d-ceef-4459-b0e7-19d75f4f12d1.png',
    bannerLinkId: 15,
    isWeb: 1,
    brandId: null,
    seqNo: 1,
    width: '1074',
    height: '1440',
    categoryId: null,
    categoryName: null,
    categoryImgUrl: null,
    productId: null,
    productName: null,
    searchKeyword: null,
    recommendedId: null,
  },
  {
    id: 217,
    name: 'WebBanner2',
    url: 'https://aws-mhsimages-bucket.s3-ap-southeast-1.amazonaws.com/sit/VapePI/images/product/af01197d-ceef-4459-b0e7-19d75f4f12d1.png',
    bannerLinkId: 8,
    isWeb: 1,
    brandId: null,
    seqNo: 2,
    width: '1074',
    height: '1440',
    categoryId: 5,
    categoryName: 'Wild Green',
    categoryImgUrl:
      'https://aws-mhsimages-bucket.s3-ap-southeast-1.amazonaws.com/sit/VapePI/images/Category/2b571540-c97b-4e33-9143-5b48ca6d43af..png',
    productId: null,
    productName: null,
    searchKeyword: null,
    recommendedId: null,
  },
  {
    id: 218,
    name: 'WebBanner3',
    url: 'https://aws-mhsimages-bucket.s3-ap-southeast-1.amazonaws.com/sit/VapePI/images/product/a3b63882-de58-40f9-8e9b-0283eee00902.png',
    bannerLinkId: 9,
    isWeb: 1,
    brandId: null,
    seqNo: 3,
    width: '1074',
    height: '1440',
    categoryId: null,
    categoryName: null,
    categoryImgUrl: null,
    productId: null,
    productName: null,
    searchKeyword: 'pod',
    recommendedId: null,
  },
];

const ADList = [
  {
    id: 204,
    name: 'MobileAds1',
    url: MobileADS,
    bannerLinkId: 7,
    isWeb: 0,
    brandId: null,
    seqNo: 2,
    width: '840',
    height: '1080',
    categoryId: null,
    categoryName: null,
    categoryImgUrl: null,
    productId: null,
    productName: null,
    searchKeyword: null,
    recommendedId: null,
  },
  {
    id: 205,
    name: 'MobileAds3',
    url: MobileADS2,
    bannerLinkId: 15,
    isWeb: 0,
    brandId: null,
    seqNo: 1,
    width: '840',
    height: '1080',
    categoryId: null,
    categoryName: null,
    categoryImgUrl: null,
    productId: null,
    productName: null,
    searchKeyword: null,
    recommendedId: null,
  },
  {
    id: 206,
    name: 'MobileAds2',
    url: MobileADS,
    bannerLinkId: 9,
    isWeb: 0,
    brandId: null,
    seqNo: 3,
    width: '840',
    height: '1080',
    categoryId: null,
    categoryName: null,
    categoryImgUrl: null,
    productId: null,
    productName: null,
    searchKeyword: 'vape',
    recommendedId: null,
  },
  {
    id: 207,
    name: 'WebAds3',
    url: 'https://aws-mhsimages-bucket.s3-ap-southeast-1.amazonaws.com/sit/VapePI/images/product/c7607b4e-07f4-4f6b-8afe-a707513c6bf7.png',
    bannerLinkId: 15,
    isWeb: 1,
    brandId: null,
    seqNo: 1,
    width: '840',
    height: '1080',
    categoryId: null,
    categoryName: null,
    categoryImgUrl: null,
    productId: null,
    productName: null,
    searchKeyword: null,
    recommendedId: null,
  },
  {
    id: 208,
    name: 'WebAds1',
    url: 'https://aws-mhsimages-bucket.s3-ap-southeast-1.amazonaws.com/sit/VapePI/images/product/29542859-fbb5-444b-a934-6a825076760d.png',
    bannerLinkId: 2,
    isWeb: 1,
    brandId: null,
    seqNo: 2,
    width: '840',
    height: '1080',
    categoryId: null,
    categoryName: null,
    categoryImgUrl: null,
    productId: null,
    productName: null,
    searchKeyword: null,
    recommendedId: null,
  },
  {
    id: 209,
    name: 'WebAds2',
    url: 'https://aws-mhsimages-bucket.s3-ap-southeast-1.amazonaws.com/sit/VapePI/images/product/c855b693-18f2-44e5-8bc2-24be80b69a07.png',
    bannerLinkId: 1,
    isWeb: 1,
    brandId: null,
    seqNo: 3,
    width: '840',
    height: '1080',
    categoryId: null,
    categoryName: null,
    categoryImgUrl: null,
    productId: null,
    productName: null,
    searchKeyword: null,
    recommendedId: null,
  },
];

const dummyUser = [
  {
    userId: 1,
    url: user_one,
  },
  {
    userId: 2,
    url: user_two,
  },
  {
    userId: 3,
    url: user_three,
  },
  {
    userId: 4,
    url: user_four,
  },
  {
    userId: 5,
    url: user_five,
  },
];
const shoplists = [
  {
    id: 1,
    name: 'United Clothing Mall',
    description: 'Fashion & Attire',
    shopRating: 90,
    url: United,
    isFollow: false,
    phoneNo: ['09978810480', '09978810480', '09978810480'],
    location: 'Kamaryut, Yangon',
    address: 'No.123, University Avnue Road\n No.123, Bargayar Road',
    promotePercent: 30,
    shopProduct: [
      {
        id: 1,
        name: 'adidas sports t-shirt',
        url: UnitedOne,
        productId: 7,

        originalPrice: 10000,
        promotePrice: 7000,
        promotePercent: 30,
        isFav: false,
        fromPrice: 0,
        toPrice: 0,
        hasFromToPrice: false,
        promoteFromPrice: null,
        promoteToPrice: null,
        totalWishList: 0,
        totalOrder: 8,
        skuValueSize: 2,
        leftQtyForFirstSkuValue: 94,
        firstSkuValue: '3%',
        firstSkuId: 1,
        rating: 4.9,
        ratingCount: 20,
      },
      {
        id: 2,
        name: 'adidas sports sneaker',
        url: UnitedTwo,
        productId: 7,

        originalPrice: 10000,
        promotePrice: 7000,
        promotePercent: 30,
        isFav: false,
        fromPrice: 0,
        toPrice: 0,
        hasFromToPrice: false,
        promoteFromPrice: null,
        promoteToPrice: null,
        totalWishList: 0,
        totalOrder: 8,
        skuValueSize: 2,
        leftQtyForFirstSkuValue: 94,
        firstSkuValue: '3%',
        firstSkuId: 1,
        rating: 4.9,
        ratingCount: 20,
      },
      {
        id: 3,
        name: 'short pants',
        url: UnitedThree,
        productId: 7,

        originalPrice: 10000,
        promotePrice: 7000,
        promotePercent: 30,
        isFav: false,
        fromPrice: 0,
        toPrice: 0,
        hasFromToPrice: false,
        promoteFromPrice: null,
        promoteToPrice: null,
        totalWishList: 0,
        totalOrder: 8,
        skuValueSize: 2,
        leftQtyForFirstSkuValue: 94,
        firstSkuValue: '3%',
        firstSkuId: 1,
        rating: 4.9,
        ratingCount: 20,
      },
      {
        id: 4,
        name: 'adidas sports t-shirt',
        url: UnitedOne,
        productId: 7,

        originalPrice: 10000,
        promotePrice: 7000,
        promotePercent: 30,
        isFav: false,
        fromPrice: 0,
        toPrice: 0,
        hasFromToPrice: false,
        promoteFromPrice: null,
        promoteToPrice: null,
        totalWishList: 0,
        totalOrder: 8,
        skuValueSize: 2,
        leftQtyForFirstSkuValue: 94,
        firstSkuValue: '3%',
        firstSkuId: 1,
        rating: 4.9,
        ratingCount: 20,
      },
      {
        id: 5,
        name: 'adidas sports sneaker',
        url: UnitedTwo,
        productId: 7,

        originalPrice: 10000,
        promotePrice: 7000,
        promotePercent: 30,
        isFav: false,
        fromPrice: 0,
        toPrice: 0,
        hasFromToPrice: false,
        promoteFromPrice: null,
        promoteToPrice: null,
        totalWishList: 0,
        totalOrder: 8,
        skuValueSize: 2,
        leftQtyForFirstSkuValue: 94,
        firstSkuValue: '3%',
        firstSkuId: 1,
        rating: 4.9,
        ratingCount: 20,
      },
      {
        id: 6,
        name: 'short pants',
        url: UnitedThree,
        productId: 7,

        originalPrice: 10000,
        promotePrice: 7000,
        promotePercent: 30,
        isFav: false,
        fromPrice: 0,
        toPrice: 0,
        hasFromToPrice: false,
        promoteFromPrice: null,
        promoteToPrice: null,
        totalWishList: 0,
        totalOrder: 8,
        skuValueSize: 2,
        leftQtyForFirstSkuValue: 94,
        firstSkuValue: '3%',
        firstSkuId: 1,
        rating: 4.9,
        ratingCount: 20,
      },
    ],
  },
  {
    id: 2,
    name: 'MAL Liquor Store',
    description: 'Alchol & Liquor',
    shopRating: 90,
    url: Liquor,
    isFollow: true,
    phoneNo: ['09978810480', '09978810480', '09978810480'],
    location: 'Yankin, Yangon',
    address: 'No.123, University Avnue Road\n No.123, Bargayar Road',
    promotePercent: 70,
    shopProduct: [
      {
        id: 1,
        name: 'adidas sports t-shirt',
        url: LiquorOne,
        productId: 7,
        originalPrice: 10000,
        promotePrice: 7000,
        promotePercent: 30,
        isFav: false,
        fromPrice: 0,
        toPrice: 0,
        hasFromToPrice: false,
        promoteFromPrice: null,
        promoteToPrice: null,
        totalWishList: 0,
        totalOrder: 8,
        skuValueSize: 2,
        leftQtyForFirstSkuValue: 94,
        firstSkuValue: '3%',
        firstSkuId: 1,
        rating: 4.9,
        ratingCount: 20,
      },
      {
        id: 2,
        name: 'adidas sports sneaker',
        url: LiquorTwo,
        productId: 7,
        originalPrice: 10000,
        promotePrice: 7000,
        promotePercent: 30,
        isFav: false,
        fromPrice: 0,
        toPrice: 0,
        hasFromToPrice: false,
        promoteFromPrice: null,
        promoteToPrice: null,
        totalWishList: 0,
        totalOrder: 8,
        skuValueSize: 2,
        leftQtyForFirstSkuValue: 94,
        firstSkuValue: '3%',
        firstSkuId: 1,
        rating: 4.9,
        ratingCount: 20,
      },
      {
        id: 3,
        name: 'short pants',
        url: LiquorThree,
        productId: 7,
        originalPrice: 10000,
        promotePrice: 7000,
        promotePercent: 30,
        isFav: false,
        fromPrice: 0,
        toPrice: 0,
        hasFromToPrice: false,
        promoteFromPrice: null,
        promoteToPrice: null,
        totalWishList: 0,
        totalOrder: 8,
        skuValueSize: 2,
        leftQtyForFirstSkuValue: 94,
        firstSkuValue: '3%',
        firstSkuId: 1,
        rating: 4.9,
        ratingCount: 20,
      },
      {
        id: 4,
        name: 'adidas sports t-shirt',
        url: LiquorOne,
        productId: 7,
        originalPrice: 10000,
        promotePrice: 7000,
        promotePercent: 30,
        isFav: false,
        fromPrice: 0,
        toPrice: 0,
        hasFromToPrice: false,
        promoteFromPrice: null,
        promoteToPrice: null,
        totalWishList: 0,
        totalOrder: 8,
        skuValueSize: 2,
        leftQtyForFirstSkuValue: 94,
        firstSkuValue: '3%',
        firstSkuId: 1,
        rating: 4.9,
        ratingCount: 20,
      },
      {
        id: 5,
        name: 'adidas sports sneaker',
        url: LiquorTwo,
        productId: 7,
        originalPrice: 10000,
        promotePrice: 7000,
        promotePercent: 30,
        isFav: false,
        fromPrice: 0,
        toPrice: 0,
        hasFromToPrice: false,
        promoteFromPrice: null,
        promoteToPrice: null,
        totalWishList: 0,
        totalOrder: 8,
        skuValueSize: 2,
        leftQtyForFirstSkuValue: 94,
        firstSkuValue: '3%',
        firstSkuId: 1,
        rating: 4.9,
        ratingCount: 20,
      },
      {
        id: 6,
        name: 'short pants',
        url: LiquorThree,
        productId: 7,
        originalPrice: 10000,
        promotePrice: 7000,
        promotePercent: 30,
        isFav: false,
        fromPrice: 0,
        toPrice: 0,
        hasFromToPrice: false,
        promoteFromPrice: null,
        promoteToPrice: null,
        totalWishList: 0,
        totalOrder: 8,
        skuValueSize: 2,
        leftQtyForFirstSkuValue: 94,
        firstSkuValue: '3%',
        firstSkuId: 1,
        rating: 4.9,
        ratingCount: 20,
      },
    ],
  },
  {
    id: 50,
    name: 'Beauty Biography Cosmetics',
    description: 'Cosmetic & Beauty',
    shopRating: 90,
    url: Beauty,
    isFollow: true,
    phoneNo: '09978810480',
    location: 'Sanchaung, Yangon',
    address: 'No.123, University Avnue Road\n No.123, Bargayar Road',
    promotePercent: 50,
    shopProduct: [
      {
        id: 1,
        name: 'adidas sports t-shirt',
        url: BeautyOne,
        productId: 7,
        originalPrice: 10000,
        promotePrice: 7000,
        promotePercent: 30,
        isFav: false,
        fromPrice: 0,
        toPrice: 0,
        hasFromToPrice: false,
        promoteFromPrice: null,
        promoteToPrice: null,
        totalWishList: 0,
        totalOrder: 8,
        skuValueSize: 2,
        leftQtyForFirstSkuValue: 94,
        firstSkuValue: '3%',
        firstSkuId: 1,
        rating: 4.9,
        ratingCount: 20,
      },
      {
        id: 2,
        name: 'adidas sports sneaker',
        url: BeautyTwo,
        productId: 7,
        originalPrice: 10000,
        promotePrice: 7000,
        promotePercent: 30,
        isFav: false,
        fromPrice: 0,
        toPrice: 0,
        hasFromToPrice: false,
        promoteFromPrice: null,
        promoteToPrice: null,
        totalWishList: 0,
        totalOrder: 8,
        skuValueSize: 2,
        leftQtyForFirstSkuValue: 94,
        firstSkuValue: '3%',
        firstSkuId: 1,
        rating: 4.9,
        ratingCount: 20,
      },
      {
        id: 3,
        name: 'short pants',
        url: BeautyThree,
        productId: 7,
        originalPrice: 10000,
        promotePrice: 7000,
        promotePercent: 30,
        isFav: false,
        fromPrice: 0,
        toPrice: 0,
        hasFromToPrice: false,
        promoteFromPrice: null,
        promoteToPrice: null,
        totalWishList: 0,
        totalOrder: 8,
        skuValueSize: 2,
        leftQtyForFirstSkuValue: 94,
        firstSkuValue: '3%',
        firstSkuId: 1,
        rating: 4.9,
        ratingCount: 20,
      },
      {
        id: 4,
        name: 'adidas sports t-shirt',
        url: BeautyOne,
        productId: 7,
        originalPrice: 10000,
        promotePrice: 7000,
        promotePercent: 30,
        isFav: false,
        fromPrice: 0,
        toPrice: 0,
        hasFromToPrice: false,
        promoteFromPrice: null,
        promoteToPrice: null,
        totalWishList: 0,
        totalOrder: 8,
        skuValueSize: 2,
        leftQtyForFirstSkuValue: 94,
        firstSkuValue: '3%',
        firstSkuId: 1,
        rating: 4.9,
        ratingCount: 20,
      },
      {
        id: 5,
        name: 'adidas sports sneaker',
        url: BeautyTwo,
        productId: 7,
        originalPrice: 10000,
        promotePrice: 7000,
        promotePercent: 30,
        isFav: false,
        fromPrice: 0,
        toPrice: 0,
        hasFromToPrice: false,
        promoteFromPrice: null,
        promoteToPrice: null,
        totalWishList: 0,
        totalOrder: 8,
        skuValueSize: 2,
        leftQtyForFirstSkuValue: 94,
        firstSkuValue: '3%',
        firstSkuId: 1,
        rating: 4.9,
        ratingCount: 20,
      },
      {
        id: 6,
        name: 'short pants',
        url: BeautyThree,
        productId: 7,
        originalPrice: 10000,
        promotePrice: 7000,
        promotePercent: 30,
        isFav: false,
        fromPrice: 0,
        toPrice: 0,
        hasFromToPrice: false,
        promoteFromPrice: null,
        promoteToPrice: null,
        totalWishList: 0,
        totalOrder: 8,
        skuValueSize: 2,
        leftQtyForFirstSkuValue: 94,
        firstSkuValue: '3%',
        firstSkuId: 1,
        rating: 4.9,
        ratingCount: 20,
      },
    ],
  },
  {
    id: 80,
    name: 'Jobby Fried Chicken',
    description: 'Fast Food & Fried',
    shopRating: 90,
    url: Fried,
    isFollow: false,
    phoneNo: ['09978810480', '09978810480', '09978810480'],
    location: 'Tarmwe, Yangon',
    address: 'No.123, University Avnue Road\nNo.123, Bargayar Road',
    promotePercent: 20,
    shopProduct: [
      {
        id: 1,
        name: 'adidas sports t-shirt',
        url: FriedOne,
        productId: 7,
        originalPrice: 10000,
        promotePrice: 7000,
        promotePercent: 30,
        isFav: false,
        fromPrice: 0,
        toPrice: 0,
        hasFromToPrice: false,
        promoteFromPrice: null,
        promoteToPrice: null,
        totalWishList: 0,
        totalOrder: 8,
        skuValueSize: 2,
        leftQtyForFirstSkuValue: 94,
        firstSkuValue: '3%',
        firstSkuId: 1,
        rating: 4.9,
        ratingCount: 20,
      },
      {
        id: 2,
        name: 'adidas sports sneaker',
        url: FriedTwo,
        productId: 7,
        originalPrice: 10000,
        promotePrice: 7000,
        promotePercent: 30,
        isFav: false,
        fromPrice: 0,
        toPrice: 0,
        hasFromToPrice: false,
        promoteFromPrice: null,
        promoteToPrice: null,
        totalWishList: 0,
        totalOrder: 8,
        skuValueSize: 2,
        leftQtyForFirstSkuValue: 94,
        firstSkuValue: '3%',
        firstSkuId: 1,
        rating: 4.9,
        ratingCount: 20,
      },
      {
        id: 3,
        name: 'short pants',
        url: FriedThree,
        productId: 7,
        originalPrice: 10000,
        promotePrice: 7000,
        promotePercent: 30,
        isFav: false,
        fromPrice: 0,
        toPrice: 0,
        hasFromToPrice: false,
        promoteFromPrice: null,
        promoteToPrice: null,
        totalWishList: 0,
        totalOrder: 8,
        skuValueSize: 2,
        leftQtyForFirstSkuValue: 94,
        firstSkuValue: '3%',
        firstSkuId: 1,
        rating: 4.9,
        ratingCount: 20,
      },
      {
        id: 4,
        name: 'adidas sports t-shirt',
        url: FriedOne,
        productId: 7,
        originalPrice: 10000,
        promotePrice: 7000,
        promotePercent: 30,
        isFav: false,
        fromPrice: 0,
        toPrice: 0,
        hasFromToPrice: false,
        promoteFromPrice: null,
        promoteToPrice: null,
        totalWishList: 0,
        totalOrder: 8,
        skuValueSize: 2,
        leftQtyForFirstSkuValue: 94,
        firstSkuValue: '3%',
        firstSkuId: 1,
        rating: 4.9,
        ratingCount: 20,
      },
      {
        id: 5,
        name: 'adidas sports sneaker',
        url: FriedTwo,
        productId: 7,
        originalPrice: 10000,
        promotePrice: 7000,
        promotePercent: 30,
        isFav: false,
        fromPrice: 0,
        toPrice: 0,
        hasFromToPrice: false,
        promoteFromPrice: null,
        promoteToPrice: null,
        totalWishList: 0,
        totalOrder: 8,
        skuValueSize: 2,
        leftQtyForFirstSkuValue: 94,
        firstSkuValue: '3%',
        firstSkuId: 1,
        rating: 4.9,
        ratingCount: 20,
      },
      {
        id: 6,
        name: 'short pants',
        url: FriedThree,
        productId: 7,
        originalPrice: 10000,
        promotePrice: 7000,
        promotePercent: 30,
        isFav: false,
        fromPrice: 0,
        toPrice: 0,
        hasFromToPrice: false,
        promoteFromPrice: null,
        promoteToPrice: null,
        totalWishList: 0,
        totalOrder: 8,
        skuValueSize: 2,
        leftQtyForFirstSkuValue: 94,
        firstSkuValue: '3%',
        firstSkuId: 1,
        rating: 4.9,
        ratingCount: 20,
      },
    ],
  },
  {
    id: 5,
    name: 'Shwe Toe Sneaker World',
    description: 'Shoes & Sneakers',
    shopRating: 90,
    url: Shwe,
    isFollow: false,
    phoneNo: ['09978810480', '09978810480', '09978810480'],
    location: 'Kyimyindaing, Yangon',
    promotePercent: 10,
    shopProduct: [
      {
        id: 1,
        name: 'adidas sports t-shirt',
        url: ShweOne,
        productId: 7,
        originalPrice: 10000,
        promotePrice: 7000,
        promotePercent: 30,
        isFav: false,
        fromPrice: 0,
        toPrice: 0,
        hasFromToPrice: false,
        promoteFromPrice: null,
        promoteToPrice: null,
        totalWishList: 0,
        totalOrder: 8,
        skuValueSize: 2,
        leftQtyForFirstSkuValue: 94,
        firstSkuValue: '3%',
        firstSkuId: 1,
        rating: 4.9,
        ratingCount: 20,
      },
      {
        id: 2,
        name: 'adidas sports sneaker',
        url: ShweTwo,
        productId: 7,
        originalPrice: 10000,
        promotePrice: 7000,
        promotePercent: 30,
        isFav: false,
        fromPrice: 0,
        toPrice: 0,
        hasFromToPrice: false,
        promoteFromPrice: null,
        promoteToPrice: null,
        totalWishList: 0,
        totalOrder: 8,
        skuValueSize: 2,
        leftQtyForFirstSkuValue: 94,
        firstSkuValue: '3%',
        firstSkuId: 1,
        rating: 4.9,
        ratingCount: 20,
      },
      {
        id: 3,
        name: 'short pants',
        url: ShweThree,
        productId: 7,
        originalPrice: 10000,
        promotePrice: 7000,
        promotePercent: 30,
        isFav: false,
        fromPrice: 0,
        toPrice: 0,
        hasFromToPrice: false,
        promoteFromPrice: null,
        promoteToPrice: null,
        totalWishList: 0,
        totalOrder: 8,
        skuValueSize: 2,
        leftQtyForFirstSkuValue: 94,
        firstSkuValue: '3%',
        firstSkuId: 1,
        rating: 4.9,
        ratingCount: 20,
      },
      {
        id: 4,
        name: 'adidas sports t-shirt',
        url: ShweOne,
        productId: 7,
        originalPrice: 10000,
        promotePrice: 7000,
        promotePercent: 30,
        isFav: false,
        fromPrice: 0,
        toPrice: 0,
        hasFromToPrice: false,
        promoteFromPrice: null,
        promoteToPrice: null,
        totalWishList: 0,
        totalOrder: 8,
        skuValueSize: 2,
        leftQtyForFirstSkuValue: 94,
        firstSkuValue: '3%',
        firstSkuId: 1,
        rating: 4.9,
        ratingCount: 20,
      },
      {
        id: 5,
        name: 'adidas sports sneaker',
        url: ShweTwo,
        productId: 7,
        originalPrice: 10000,
        promotePrice: 7000,
        promotePercent: 30,
        isFav: false,
        fromPrice: 0,
        toPrice: 0,
        hasFromToPrice: false,
        promoteFromPrice: null,
        promoteToPrice: null,
        totalWishList: 0,
        totalOrder: 8,
        skuValueSize: 2,
        leftQtyForFirstSkuValue: 94,
        firstSkuValue: '3%',
        firstSkuId: 1,
        rating: 4.9,
        ratingCount: 20,
      },
      {
        id: 6,
        name: 'short pants',
        url: ShweThree,
        productId: 7,
        originalPrice: 10000,
        promotePrice: 7000,
        promotePercent: 30,
        isFav: false,
        fromPrice: 0,
        toPrice: 0,
        hasFromToPrice: false,
        promoteFromPrice: null,
        promoteToPrice: null,
        totalWishList: 0,
        totalOrder: 8,
        skuValueSize: 2,
        leftQtyForFirstSkuValue: 94,
        firstSkuValue: '3%',
        firstSkuId: 1,
        rating: 4.9,
        ratingCount: 20,
      },
    ],
  },
];
const branches = [
  {
    id: 1,
    branchName: 'Main',
    phoneNo: '09458585848',
    email: 'example@gmail.com',
    address:
      'No 458880, Bo Gyoke Street, Veteran Ward, Chan Mya Thar Si, Mandalay',
  },
  {
    id: 2,
    branchName: 'Alone',
    phoneNo: '09458585848',
    address:
      'No 458880, Bo Gyoke Street, Veteran Ward, Chan Mya Thar Si, Mandalay',
    email: 'example@gmail.com',
  },
  {
    id: 3,
    branchName: 'Bahan',
    phoneNo: '09458585848',
    email: 'example@gmail.com',
    address:
      'No 458880, Bo Gyoke Street, Veteran Ward, Chan Mya Thar Si, Mandalay',
  },
];

const flashSale = {
  shopName: 'AYAZay',
  description: 'Super Flash Deals',
  startDate: '2023-04-12T17:30:00.000Z',
  endDate: '2023-07-19T17:30:00.000Z',
  mainUrl: FlashSaleBg,
  flashSaleProduct: [
    {
      productId: 7,
      url: FlashOne,
      name: 'Double mass increase your muscle ',
      originalPrice: 10000,
      promotePrice: 7000,
      promotePercent: 30,
      isFav: false,
      fromPrice: 0,
      toPrice: 0,
      hasFromToPrice: false,
      promoteFromPrice: null,
      promoteToPrice: null,
      totalWishList: 0,
      totalOrder: 8,
      skuValueSize: 2,
      leftQtyForFirstSkuValue: 4,
      firstSkuValue: '3%',
      firstSkuId: 1,
      rating: 4.9,
      ratingCount: 20,
    },
    {
      productId: 8,
      url: FlashTwo,
      name: 'Super Effective Bleaching liquid',
      originalPrice: 10000,
      promotePrice: 7000,
      promotePercent: 30,
      isFav: false,
      fromPrice: 0,
      toPrice: 0,
      hasFromToPrice: false,
      promoteFromPrice: null,
      promoteToPrice: null,
      totalWishList: 0,
      totalOrder: 8,
      skuValueSize: 2,
      leftQtyForFirstSkuValue: 4,
      firstSkuValue: '3%',
      firstSkuId: 1,
      rating: 4.9,
      ratingCount: 20,
    },
    {
      productId: 9,
      url: FlashThree,
      name: 'Delicious Strawberry Flavour Cereal',
      originalPrice: 10000,
      promotePrice: 7000,
      promotePercent: 30,
      isFav: false,
      fromPrice: 0,
      toPrice: 0,
      hasFromToPrice: false,
      promoteFromPrice: null,
      promoteToPrice: null,
      totalWishList: 0,
      totalOrder: 8,
      skuValueSize: 2,
      leftQtyForFirstSkuValue: 4,
      firstSkuValue: '3%',
      firstSkuId: 1,
      rating: 4.9,
      ratingCount: 20,
    },
    {
      productId: 10,
      url: FlashThree,
      name: 'Delicious Strawberry Flavour Cereal',
      originalPrice: 10000,
      promotePrice: 7000,
      promotePercent: 30,
      isFav: false,
      fromPrice: 0,
      toPrice: 0,
      hasFromToPrice: false,
      promoteFromPrice: null,
      promoteToPrice: null,
      totalWishList: 0,
      totalOrder: 8,
      skuValueSize: 2,
      leftQtyForFirstSkuValue: 4,
      firstSkuValue: '3%',
      firstSkuId: 1,
      rating: 4.9,
      ratingCount: 20,
    },
    {
      productId: 11,
      url: FlashThree,
      name: 'Delicious Strawberry Flavour Cereal',
      originalPrice: 10000,
      promotePrice: 7000,
      promotePercent: 30,
      isFav: false,
      fromPrice: 0,
      toPrice: 0,
      hasFromToPrice: false,
      promoteFromPrice: null,
      promoteToPrice: null,
      totalWishList: 0,
      totalOrder: 8,
      skuValueSize: 2,
      leftQtyForFirstSkuValue: 4,
      firstSkuValue: '3%',
      firstSkuId: 1,
      rating: 4.9,
      ratingCount: 20,
    },
    {
      productId: 12,
      url: FlashThree,
      name: 'Delicious Strawberry Flavour Cereal',
      originalPrice: 10000,
      promotePrice: 7000,
      promotePercent: 30,
      isFav: false,
      fromPrice: 0,
      toPrice: 0,
      hasFromToPrice: false,
      promoteFromPrice: null,
      promoteToPrice: null,
      totalWishList: 0,
      totalOrder: 8,
      skuValueSize: 2,
      leftQtyForFirstSkuValue: 4,
      firstSkuValue: '3%',
      firstSkuId: 1,
      rating: 4.9,
      ratingCount: 20,
    },
    {
      productId: 13,
      url: FlashThree,
      name: 'Delicious Strawberry Flavour Cereal',
      originalPrice: 10000,
      promotePrice: 7000,
      promotePercent: 30,
      isFav: false,
      fromPrice: 0,
      toPrice: 0,
      hasFromToPrice: false,
      promoteFromPrice: null,
      promoteToPrice: null,
      totalWishList: 0,
      totalOrder: 8,
      skuValueSize: 2,
      leftQtyForFirstSkuValue: 4,
      firstSkuValue: '3%',
      firstSkuId: 1,
      rating: 4.9,
      ratingCount: 20,
    },
  ],
};

const specialSale = [
  {
    id: 1,
    name: 'Best Offer',
    specialSaleProduct: [
      {
        productId: 7,
        url: FlashOne,
        name: 'Double mass increase your muscle ',
        originalPrice: 10000,
        promotePrice: 7000,
        promotePercent: 30,
        isFav: false,
        fromPrice: 0,
        toPrice: 0,
        hasFromToPrice: false,
        promoteFromPrice: null,
        promoteToPrice: null,
        totalWishList: 0,
        totalOrder: 8,
        skuValueSize: 2,
        leftQtyForFirstSkuValue: 4,
        firstSkuValue: '3%',
        firstSkuId: 1,
        rating: 4.9,
        ratingCount: 20,
      },
      {
        productId: 8,
        url: FlashTwo,
        name: 'Super Effective Bleaching liquid',
        originalPrice: 10000,
        promotePrice: 7000,
        promotePercent: 30,
        isFav: false,
        fromPrice: 0,
        toPrice: 0,
        hasFromToPrice: false,
        promoteFromPrice: null,
        promoteToPrice: null,
        totalWishList: 0,
        totalOrder: 8,
        skuValueSize: 2,
        leftQtyForFirstSkuValue: 4,
        firstSkuValue: '3%',
        firstSkuId: 1,
        rating: 4.9,
        ratingCount: 20,
      },
      {
        productId: 9,
        url: FlashThree,
        name: 'Delicious Strawberry Flavour Cereal',
        originalPrice: 10000,
        promotePrice: 7000,
        promotePercent: 30,
        isFav: false,
        fromPrice: 0,
        toPrice: 0,
        hasFromToPrice: false,
        promoteFromPrice: null,
        promoteToPrice: null,
        totalWishList: 0,
        totalOrder: 8,
        skuValueSize: 2,
        leftQtyForFirstSkuValue: 4,
        firstSkuValue: '3%',
        firstSkuId: 1,
        rating: 4.9,
        ratingCount: 20,
      },
      {
        productId: 10,
        url: FlashThree,
        name: 'Delicious Strawberry Flavour Cereal',
        originalPrice: 10000,
        promotePrice: 7000,
        promotePercent: 30,
        isFav: false,
        fromPrice: 0,
        toPrice: 0,
        hasFromToPrice: false,
        promoteFromPrice: null,
        promoteToPrice: null,
        totalWishList: 0,
        totalOrder: 8,
        skuValueSize: 2,
        leftQtyForFirstSkuValue: 4,
        firstSkuValue: '3%',
        firstSkuId: 1,
        rating: 4.9,
        ratingCount: 20,
      },
      {
        productId: 11,
        url: FlashThree,
        name: 'Delicious Strawberry Flavour Cereal',
        originalPrice: 10000,
        promotePrice: 7000,
        promotePercent: 30,
        isFav: false,
        fromPrice: 0,
        toPrice: 0,
        hasFromToPrice: false,
        promoteFromPrice: null,
        promoteToPrice: null,
        totalWishList: 0,
        totalOrder: 8,
        skuValueSize: 2,
        leftQtyForFirstSkuValue: 4,
        firstSkuValue: '3%',
        firstSkuId: 1,
        rating: 4.9,
        ratingCount: 20,
      },
      {
        productId: 12,
        url: FlashThree,
        name: 'Delicious Strawberry Flavour Cereal',
        originalPrice: 10000,
        promotePrice: 7000,
        promotePercent: 30,
        isFav: false,
        fromPrice: 0,
        toPrice: 0,
        hasFromToPrice: false,
        promoteFromPrice: null,
        promoteToPrice: null,
        totalWishList: 0,
        totalOrder: 8,
        skuValueSize: 2,
        leftQtyForFirstSkuValue: 4,
        firstSkuValue: '3%',
        firstSkuId: 1,
        rating: 4.9,
        ratingCount: 20,
      },
      {
        productId: 13,
        url: FlashThree,
        name: 'Delicious Strawberry Flavour Cereal',
        originalPrice: 10000,
        promotePrice: 7000,
        promotePercent: 30,
        isFav: false,
        fromPrice: 0,
        toPrice: 0,
        hasFromToPrice: false,
        promoteFromPrice: null,
        promoteToPrice: null,
        totalWishList: 0,
        totalOrder: 8,
        skuValueSize: 2,
        leftQtyForFirstSkuValue: 4,
        firstSkuValue: '3%',
        firstSkuId: 1,
        rating: 4.9,
        ratingCount: 20,
      },
    ],
  },
  {
    id: 2,
    name: 'Mahar Thingyan Special Sale',
    specialSaleProduct: [
      {
        productId: 7,
        url: FlashOne,
        name: 'Double mass increase your muscle ',
        originalPrice: 10000,
        promotePrice: 7000,
        promotePercent: 30,
        isFav: false,
        fromPrice: 0,
        toPrice: 0,
        hasFromToPrice: false,
        promoteFromPrice: null,
        promoteToPrice: null,
        totalWishList: 0,
        totalOrder: 8,
        skuValueSize: 2,
        leftQtyForFirstSkuValue: 4,
        firstSkuValue: '3%',
        firstSkuId: 1,
        rating: 4.9,
        ratingCount: 20,
      },
      {
        productId: 8,
        url: FlashTwo,
        name: 'Super Effective Bleaching liquid',
        originalPrice: 10000,
        promotePrice: 7000,
        promotePercent: 30,
        isFav: false,
        fromPrice: 0,
        toPrice: 0,
        hasFromToPrice: false,
        promoteFromPrice: null,
        promoteToPrice: null,
        totalWishList: 0,
        totalOrder: 8,
        skuValueSize: 2,
        leftQtyForFirstSkuValue: 4,
        firstSkuValue: '3%',
        firstSkuId: 1,
        rating: 4.9,
        ratingCount: 20,
      },
      {
        productId: 9,
        url: FlashThree,
        name: 'Delicious Strawberry Flavour Cereal',
        originalPrice: 10000,
        promotePrice: 7000,
        promotePercent: 30,
        isFav: false,
        fromPrice: 0,
        toPrice: 0,
        hasFromToPrice: false,
        promoteFromPrice: null,
        promoteToPrice: null,
        totalWishList: 0,
        totalOrder: 8,
        skuValueSize: 2,
        leftQtyForFirstSkuValue: 4,
        firstSkuValue: '3%',
        firstSkuId: 1,
        rating: 4.9,
        ratingCount: 20,
      },
      {
        productId: 10,
        url: FlashThree,
        name: 'Delicious Strawberry Flavour Cereal',
        originalPrice: 10000,
        promotePrice: 7000,
        promotePercent: 30,
        isFav: false,
        fromPrice: 0,
        toPrice: 0,
        hasFromToPrice: false,
        promoteFromPrice: null,
        promoteToPrice: null,
        totalWishList: 0,
        totalOrder: 8,
        skuValueSize: 2,
        leftQtyForFirstSkuValue: 4,
        firstSkuValue: '3%',
        firstSkuId: 1,
        rating: 4.9,
        ratingCount: 20,
      },
      {
        productId: 11,
        url: FlashThree,
        name: 'Delicious Strawberry Flavour Cereal',
        originalPrice: 10000,
        promotePrice: 7000,
        promotePercent: 30,
        isFav: false,
        fromPrice: 0,
        toPrice: 0,
        hasFromToPrice: false,
        promoteFromPrice: null,
        promoteToPrice: null,
        totalWishList: 0,
        totalOrder: 8,
        skuValueSize: 2,
        leftQtyForFirstSkuValue: 4,
        firstSkuValue: '3%',
        firstSkuId: 1,
        rating: 4.9,
        ratingCount: 20,
      },
      {
        productId: 12,
        url: FlashThree,
        name: 'Delicious Strawberry Flavour Cereal',
        originalPrice: 10000,
        promotePrice: 7000,
        promotePercent: 30,
        isFav: false,
        fromPrice: 0,
        toPrice: 0,
        hasFromToPrice: false,
        promoteFromPrice: null,
        promoteToPrice: null,
        totalWishList: 0,
        totalOrder: 8,
        skuValueSize: 2,
        leftQtyForFirstSkuValue: 4,
        firstSkuValue: '3%',
        firstSkuId: 1,
        rating: 4.9,
        ratingCount: 20,
      },
      {
        productId: 13,
        url: FlashThree,
        name: 'Delicious Strawberry Flavour Cereal',
        originalPrice: 10000,
        promotePrice: 7000,
        promotePercent: 30,
        isFav: false,
        fromPrice: 0,
        toPrice: 0,
        hasFromToPrice: false,
        promoteFromPrice: null,
        promoteToPrice: null,
        totalWishList: 0,
        totalOrder: 8,
        skuValueSize: 2,
        leftQtyForFirstSkuValue: 4,
        firstSkuValue: '3%',
        firstSkuId: 1,
        rating: 4.9,
        ratingCount: 20,
      },
    ],
  },
];

const location = [
  {
    id: 110,
    labelName: 'Home',
    cityId: 260,
    cityName: 'Yangon',
    townshipId: 27,
    townshipName: 'Ahlone',
    address: 'No-(123), Sin Min Zay \nNo-(214), Sin Min Zay',
    landmark: 'MyoMa Zay',
    selected: true,
    updatedDate: '2023-03-30T12:37:55.778496',
  },
  {
    id: 112,
    labelName: 'Work',
    cityId: 260,
    cityName: 'Yangon',
    townshipId: 27,
    townshipName: 'Ahlone',
    address: 'No-(123), Sin Min Zay \nNo-(214), Sin Min Zay',
    landmark: 'MyoMa Zay',
    selected: true,
    updatedDate: '2023-03-30T12:37:55.778496',
  },
  {
    id: 111,
    labelName: 'Other',
    cityId: 260,
    cityName: 'Yangon',
    townshipId: 27,
    townshipName: 'Ahlone',
    address: 'No-(123), Sin Min Zay \nNo-(214), Sin Min Zay',
    landmark: 'MyoMa Zay',
    selected: true,
    updatedDate: '2023-03-30T12:37:55.778496',
  },
];
const brands = [
  {
    id: 63,
    name: 'Nintendo®',
    logoUrl: Nintendo,
    url: Nintendo,
    backgroundUrl: NintendoBg,
    description:
      '"Good For Your Pet” is what best describes our Goodies Pet Treat.\n\nWith many benefits to your pets, especially dogs and cats, we are sure that your pets will get  more healthy. Goodies have many varieties to choose for all breeds and ages of your pets. It is not just any treats but it is Goodies Pet treats. We as Goodies pet treats are dedicated to providing our pet products to help you give your pet  a healthy, happy life. Whether you\'re looking for treats  with nutrition, dental care, bakery, jerky, chews, or etc. Goodies treats are what you can trust and be confident in.',
    isPopular: true,
    updatedDate: '0001-01-01T00:00:00',
    serNo: 0,
    facebookUrl: null,
    messengerUrl: null,
    products: [
      {
        productId: 2194,
        url: N_One,
        name: 'Nitendo Switch Lite',
        originalPrice: 3000,
        promotePrice: 0,
        promotePercent: 0,
        hasFromToPrice: false,
        fromPrice: 0,
        toPrice: 0,
        promoteFromPrice: 0,
        promoteToPrice: 0,
        createdDate: '2022-11-30T15:46:56.1189099',
        isFav: false,
      },
      {
        productId: 2195,
        url: N_Two,
        name: 'Immortal Fenyx Switch Edition',
        originalPrice: 3000,
        promotePrice: 0,
        promotePercent: 0,
        hasFromToPrice: false,
        fromPrice: 0,
        toPrice: 0,
        promoteFromPrice: 0,
        promoteToPrice: 0,
        createdDate: '2022-11-30T15:46:56.1189099',
        isFav: false,
      },
      {
        productId: 2199,
        url: N_Three,
        name: ' Nitendo Switch OLED Version',
        originalPrice: 3000,
        promotePrice: 0,
        promotePercent: 0,
        hasFromToPrice: false,
        fromPrice: 0,
        toPrice: 0,
        promoteFromPrice: 0,
        promoteToPrice: 0,
        createdDate: '2022-11-30T15:46:56.1189099',
        isFav: false,
      },
    ],
  },
  {
    id: 64,
    name: 'Vans Off The Wall Aesthetic Shoes',
    logoUrl: VanOfTheWall,
    url: VanOfTheWall,
    description:
      "HaisenPet is the dust-free bulk normal ball shape bentonite cat litter ball shape bentonite cat litter. It has outstanding absorption and odour lock formula which helps to absorb the cat's urine and eliminate the bad smells that come from cats' faeces and ammonia. Its instant clumping ability provides you with easy scooping and wet granules won't stick to your cats' paws. Bentonite cat litter is safe and no toxic additives. 99.9% Dust-free, safe to people and pets. Natural hygienic products, eco-friendly. Added into several flavours including apple, rose, lavender, coffee, lemon, etc. Red and blue particles are beautiful & enjoyable.",
    isPopular: false,
    updatedDate: '0001-01-01T00:00:00',
    serNo: 0,
    facebookUrl: null,
    messengerUrl: null,
  },
  {
    id: 67,
    name: 'Midea Electronics',
    logoUrl: Media,
    url: Media,
    description:
      'MyPet offers quality products and accessories for your happier pets. Find all kinds of pet food, snacks, accessories, supplies, clothes and more.',
    isPopular: false,
    updatedDate: '0001-01-01T00:00:00',
    serNo: 0,
    facebookUrl: '',
    messengerUrl: '',
  },
  {
    id: 69,
    name: 'Xiaomi Co., Ltd',
    logoUrl: Mi,
    url: Mi,
    description:
      'A-Pro is a part of the Perfect Companion Group Co. Ltd, a company that plays a huge role in pet products.',
    isPopular: false,
    updatedDate: '0001-01-01T00:00:00',
    serNo: 0,
    facebookUrl: '',
    messengerUrl: '',
  },
  {
    id: 70,
    name: 'Toyota Motors',
    logoUrl: Toyota,
    url: Toyota,
    description:
      'Yabeibi is a branded enterprises which supplys pets products. We pursue fashion and perfect. Continuous Innovation is to meet market needs.',
    isPopular: false,
    updatedDate: '0001-01-01T00:00:00',
    serNo: 0,
    facebookUrl: '',
    messengerUrl: '',
  },
  {
    id: 71,
    name: 'Sony Electronics & Ent',
    logoUrl: Sony,
    url: Sony,
    description:
      'Don’t complicate your dog’s food. Get to the meat of everything your dog both loves and needs with one of Purina ALPO dog food’s delicious wet or dry recipes.',
    isPopular: false,
    updatedDate: '0001-01-01T00:00:00',
    serNo: 0,
    facebookUrl: '',
    messengerUrl: '',
  },
  {
    id: 51,
    name: 'Sony Electronics & Ent',
    logoUrl: Sony,
    url: Sony,
    description:
      'Don’t complicate your dog’s food. Get to the meat of everything your dog both loves and needs with one of Purina ALPO dog food’s delicious wet or dry recipes.',
    isPopular: false,
    updatedDate: '0001-01-01T00:00:00',
    serNo: 0,
    facebookUrl: '',
    messengerUrl: '',
  },
];

const mainCategoryDetail = [
  {
    id: 8,
    productCategoryId: 18,
    name: 'Electronic',
    description: 'Electronic & Devices',
    url: ElectCat,
    backgroundUrl: MobilePhoneBg,
    subCategory1: [
      {
        id: 32,
        name: 'Shoe & Sneakers',
        url: ShweOne,
        subCategory2: [
          {
            id: 1,
            name: 'Sneakers',
            url: ShweTwo,
          },
          {
            id: 2,
            name: 'Shoe',
            url: ShweThree,
          },
        ],
      },
      {
        id: 33,
        name: 'Jack & Outfit',
        url: Shirt,
        subCategory2: [
          {
            id: 1,
            name: 'Sneakers',
            url: ShweTwo,
          },
          {
            id: 2,
            name: 'Shoe',
            url: ShweThree,
          },
        ],
      },
      {
        id: 34,
        name: 'High Performance Tyre',
        url: 'https://aws-mhsimages-bucket.s3-ap-southeast-1.amazonaws.com/sit/Tyre78/images/Category/d43636ca-9e83-4de7-9566-b0fa696edef6..png',
        subCategory2: [
          {
            id: 1,
            name: 'Sneakers',
            url: ShweTwo,
          },
          {
            id: 2,
            name: 'Shoe',
            url: ShweThree,
          },
        ],
      },
    ],
    brand: [
      {
        mainCategoryId: 17,
        brandId: 11,
        brandName: 'Nintendo',
        url: Nintendo,
        logoUrl: null,
        description: null,
      },
      {
        mainCategoryId: 17,
        brandId: 12,
        brandName: 'Sony',
        url: Sony,
        logoUrl: null,
        description: null,
      },
      {
        mainCategoryId: 17,
        brandId: 13,
        brandName: 'Xiaomi',
        url: Mi,
        logoUrl: null,
        description: null,
      },
    ],
  },
  {
    id: 9,
    productCategoryId: 19,
    name: 'Grocerey & Food',
    description: 'Grocery & Food',
    url: GroceryCat,
    backgroundUrl: MobileHealthBg,
    subCategory1: [
      {
        id: 35,
        name: 'Dummy Sub Health Cat',
        url: Health,
        subCategory2: [],
      },
      {
        id: 36,
        name: 'Dummy Sub Health Cat',
        url: Health,
        subCategory2: [],
      },
      {
        id: 37,
        name: 'Dummy Sub Health Cat',
        url: Health,
        subCategory2: [],
      },
    ],
    brand: [
      {
        mainCategoryId: 17,
        brandId: 11,
        brandName: 'Toyota',
        url: Toyota,
        logoUrl: null,
        description: null,
      },
      {
        mainCategoryId: 17,
        brandId: 12,
        brandName: 'Toyota',
        url: Toyota,
        logoUrl: null,
        description: null,
      },
      {
        mainCategoryId: 17,
        brandId: 13,
        brandName: 'Toyota',
        url: Toyota,
        logoUrl: null,
        description: null,
      },
    ],
  },
  {
    id: 17,
    productCategoryId: 27,
    name: 'Fashion & Attire',
    description: 'Fashion & Attire',
    url: FashCat,
    backgroundUrl: MobileFashion,
    subCategory1: [
      {
        id: 38,
        name: 'Dummy Fashion One',
        url: Shirt,
        subCategory2: [],
      },
      {
        id: 39,
        name: 'Dummy Fashion One',
        url: Shirt,
        subCategory2: [],
      },
    ],
    brand: [
      {
        mainCategoryId: 17,
        brandId: 11,
        brandName: 'Vans Off The Wall',
        url: VanOfTheWall,
        logoUrl: null,
        description: null,
      },
      {
        mainCategoryId: 17,
        brandId: 12,
        brandName: 'Vans Off The Wall',
        url: VanOfTheWall,
        logoUrl: null,
        description: null,
      },
      {
        mainCategoryId: 17,
        brandId: 13,
        brandName: 'Vans Off The Wall',
        url: VanOfTheWall,
        logoUrl: null,
        description: null,
      },
    ],
  },
];

export {
  buyOneGetOne,
  banner,
  ADList,
  recommend,
  reward,
  promotions,
  latestProduct,
  getAllProductListsBuyer,
  brands,
  mainCategory,
  shoplists,
  flashSale,
  specialSale,
  dummyUser,
  location,
  mainCategoryDetail,
  branches,
};
